/**
 * Evolveum Day Off Planner API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LeaveRequestApiModel { 
    readonly id: number;
    readonly leaveType: number;
    readonly user: number;
    readonly fromDate: Date;
    readonly toDate: Date;
    readonly status: LeaveRequestApiModel.StatusEnum;
}
export namespace LeaveRequestApiModel {
    export type StatusEnum = 'APPROVED' | 'REJECTED' | 'PENDING' | 'CANCELLED';
    export const StatusEnum = {
        APPROVED: 'APPROVED' as StatusEnum,
        REJECTED: 'REJECTED' as StatusEnum,
        PENDING: 'PENDING' as StatusEnum,
        CANCELLED: 'CANCELLED' as StatusEnum
    };
}