/**
 * Evolveum Day Off Planner API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { LeaveRequestApprovalApiModel } from './leaveRequestApprovalApiModel';


export interface LeaveRequestWithApprovalsApiModel { 
    readonly id: string;
    readonly leaveType: string;
    readonly user: string;
    readonly fromDate: Date;
    readonly toDate: Date;
    readonly status: LeaveRequestWithApprovalsApiModel.StatusEnum;
    readonly approvals: Array<LeaveRequestApprovalApiModel>;
}
export namespace LeaveRequestWithApprovalsApiModel {
    export type StatusEnum = 'APPROVED' | 'REJECTED' | 'PENDING' | 'CANCELLED';
    export const StatusEnum = {
        APPROVED: 'APPROVED' as StatusEnum,
        REJECTED: 'REJECTED' as StatusEnum,
        PENDING: 'PENDING' as StatusEnum,
        CANCELLED: 'CANCELLED' as StatusEnum
    };
}